[project]
name = "poetry-greeting"
version = "0.1.0"
description = ""
authors = [
    {name = "Mike Verso",email = "mikegluhenkiy1987@gmail.com"}
]
requires-python = "^3.12"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "rich (>=15.0.0,<16.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
